name: C++ tests
on:
  push:
    branches:
      - main
      - dev

jobs:
  prop-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build GRSS library
        run: |
          source initialize.sh
          source build_cpp.sh -clean
      - name: Run tests
        run: |
          cd tests/cpp/prop
          ./didymos.out
          ./spk_map.out
