name: C++ tests
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/cpp/**'

jobs:
  prop-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build GRSS library
        run: |
          source initialize.sh --tm-overwrite
          source build_cpp.sh -clean
      - name: Run tests
        run: |
          cd tests/cpp/prop
          ./apophis.out
          ./didymos.out
          ./spk_map.out
