name: C++ tests
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/cpp_tests.yml'
      - 'include/**'
      - 'src/**'
      - 'tests/cpp/**'
      - 'grss/version.txt'

jobs:
  prop-only:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build GRSS library
        run: |
          cd ./extern/
          python3 get_cspice.py
          cd ..
          python3 -m venv ./venv
          source ./venv/bin/activate
          source initialize.sh
          source build_cpp.sh -clean
      - name: Run tests
        run: |
          cd tests/cpp/prop
          ./pck_map.out
          ./spk_map.out
          ./apophis.out
          ./didymos.out
