name: C++ tests
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/cpp_tests.yml'
      - 'include/**'
      - 'src/**'
      - 'tests/cpp/**'

jobs:
  prop-only:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build GRSS library
        run: |
          source initialize.sh
          source build_cpp.sh -clean
      - name: Run tests
        run: |
          cd tests/cpp/prop
          ./pck_map.out
          ./spk_map.out
          ./apophis.out
          ./didymos.out
