name: Build docs
on:
  push:
    branches:
      - main
      - dev

jobs:
  sphinx:
    runs-on: macos-14
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.2.0'
      - name: Install GRSS (including dependencies)
        run: |
          python3 -m pip install --upgrade pip
          brew install pandoc doxygen
          source initialize.sh
          pip3 install .
      - name: Build docs
        run: |
          python3 -m pip install sphinx-book-theme==1.0.1 pydata-sphinx-theme==0.15.2
          python3 -m pip install ipython sphinx sphinx-copybutton sphinx-gallery nbsphinx sphinx-favicon breathe
          source build_cpp.sh
          cp build/libgrss* grss/
          cd docs
          make clean html
          cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
