name: Build docs
on:
  push:
    branches:
      - main
      - dev

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install GRSS (including dependencies)
        run: |
          python3 -m pip install --upgrade pip
          source initialize.sh
          # brew install geos
          pip3 install basemap
          pip3 install .
      - name: Build docs
        run: |
          python3 -m pip install sphinx sphinx-copybutton sphinx-gallery nbsphinx sphinx-book-theme sphinx-favicon
          sudo apt-get install pandoc
          source build_cpp.sh
          cp build/prop_simulation* grss/prop
          cd docs
          make clean html
          cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
