name: JOSS build
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/joss.yml'
      - 'joss/**'

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: ./joss/joss_paper.md
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: paper
          path: ./joss/paper.pdf
