name: Build and Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
    build:
      name: Build Python 🐍 distributions 📦 to PyPI and TestPyPI
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.8"
        - name: Initialize repository
          run: |
            source initialize.sh
        - name: Build python distributions
          run: source build_python.sh
    publish:
      name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
      needs: build
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.8"
        - name: Publish to Test PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository-url: https://test.pypi.org/legacy/
        - name: Publish to PyPI
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
