name: Publish to PyPI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
    build:
      name: Build Python distributions
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            submodules: true
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.8"
        - name: Initialize repository
          run: |
            source initialize.sh
        - name: Build python distributions
          run: source build_python.sh
        - name: Upload distribution for next job
          uses: actions/upload-artifact@master
          with:
            name: dist-${{ matrix.os }}
            path: dist
    publish:
      name: Publish to PyPI and TestPyPI
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download Ubuntu distribution from previous job
          uses: actions/download-artifact@master
          with:
            name: dist-ubuntu-latest
            path: dist
        - name: Download MacOS distribution from previous job
          uses: actions/download-artifact@master
          with:
            name: dist-macos-latest
            path: dist
        - name: Show files
          run: ls -l dist
        - name: Publish to Test PyPI
          if: github.ref == 'refs/heads/dev'
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository-url: https://test.pypi.org/legacy/
        - name: Publish to PyPI
          if: github.ref == 'refs/heads/main'
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
