name: Python tests
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/python_tests.yml'
      - 'include/**'
      - 'src/**'
      - 'grss/**'
      - 'tests/python/**'

jobs:
  prop-and-fit:
    runs-on: macos-14
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.1.0'
      - name: Install GRSS (including dependencies)
        run: |
          python3 -m pip install --upgrade pip
          brew install doxygen
          source initialize.sh
          pip3 install .
      - name: Run tests
        run: |
          python3 -m pip install jupyter
          cd tests/python
          ./run_tests.sh prop
          ./run_tests.sh fit
